-- MySQL Script generated by MySQL Workbench
-- 12/09/15 11:22:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- author: @bkupfer

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema losvinedos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `losvinedos` DEFAULT CHARACTER SET utf8 ;
USE `losvinedos` ;

-- -----------------------------------------------------
-- Table `losvinedos`.`Kardex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `losvinedos`.`Kardex` (
  `sku` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(100) NOT NULL,
  `stock` INT NULL,
  `class` VARCHAR(1) NULL,
  `score` INT NULL,
  `last_updated` DATE NULL,
  PRIMARY KEY (`sku`),
  UNIQUE INDEX `sku_UNIQUE` (`sku` ASC),
  UNIQUE INDEX `item_name_UNIQUE` (`item_name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `losvinedos`.`Kardex`
-- -----------------------------------------------------
START TRANSACTION;
USE `losvinedos`;
INSERT INTO `losvinedos`.`Kardex` (`sku`, `item_name`, `stock`, `class`, `score`, `last_update`) 
VALUES 
	(0, 'item1', 100, 'A', 0, NULL),
	(1, 'item2', 80, 'A', 0, NULL),
	(3, 'item4', 50, 'A', 0, NULL),
	(2, 'item3', 20, 'A', 0, NULL),
	(4, 'item5', 10, 'A', 0, NULL),
	(5, 'item6', 40, 'B', 0, NULL),
	(6, 'item7', 20, 'B', 0, NULL),
	(7, 'item8', 45, 'B', 0, NULL),
	(8, 'item9', 60, 'B', 0, NULL),
	(9, 'item10', 50, 'B', 0, NULL),
	(10, 'item11', 120, 'B', 0, NULL),
	(11, 'item12', 100, 'B', 0, NULL),
	(12, 'item13', 60, 'B', 0, NULL),
	(13, 'item14', 70, 'B', 0, NULL),
	(14, 'item15', 0, 'B', 0, NULL),
	(15, 'item16', 100, 'C', 0, NULL),
	(16, 'item17', 20, 'C', 0, NULL),
	(17, 'item18', 50, 'C', 0, NULL),
	(18, 'item19', 15, 'C', 0, NULL),
	(19, 'item20', 30, 'C', 0, NULL),
	(20, 'item21', 40, 'C', 0, NULL),
	(21, 'item22', 0, 'C', 0, NULL),
	(22, 'item23', 0, 'C', 0, NULL),
	(23, 'item24', 10, 'C', 0, NULL),
	(24, 'item25', 0, 'C', 0, NULL),
	(25, 'item26', 40, 'C', 0, NULL),
	(26, 'item27', 100, 'C', 0, NULL),
	(27, 'item28', 120, 'C', 0, NULL),
	(28, 'item29', 80, 'C', 0, NULL),
	(29, 'item30', 50, 'C', 0, NULL);

COMMIT;
